### ISSUE TITLE
How to collaborate on a fork?

### ISSUE THREAD

**Issue by ironfist** [githubschool/foundations-4-28-15#170]
if a developer 1 forks the master, it creates the repo branch in his local account.  How does developer 2 contribute to this?  We are using Enterprise GitHub.  We want to control who can commit to master, but not make it hard for multiple developers to work on a feature.  If we just branch it in the same repo, we can't prevent them from merging to master.

**Comment by patrickmckenna** [comment]
@ironfist Great question. We'll be getting to forks later in this class, time permitting (majority is asking us to slow down a bit right now).
