### ISSUE TITLE
Branch access

### ISSUE THREAD

**Issue by ironfist** [githubschool/foundations-4-28-15#189]
Is it possible to restrict access on a branch (or better yet, master)?

**Comment by patrickmckenna** [comment]
@ironfist No, there aren't branch level permissions, and in most cases I've seen that's a good thing. You'll want to use forks for access control. You could either have everyone fork the canonical repo and submit PRs back to it, or have the blessed group fork the main repo and treat that fork as the canonical version (e.g. only deploy from it).
