### ISSUE TITLE
My issue doesn't have a check box

### ISSUE THREAD

**Issue by cnmontreal** [githubschool/foundations-4-28-15#191]
- [ ] sample 3
- [ ] sample 4

**Comment by githubteacher** [comment]
This is an example of a checkbox:
- [ ] sample 1
- [ ] sample 2

**Comment by ipuigdollers** [comment]
I m afraid he/she means a checkbox on the left hand side in the issues list. Is that possible. It happens to me as well

**Comment by cnmontreal** [comment]
Thanks!
