### ISSUE TITLE
I don't have the checkbox for adding label, etc

### ISSUE THREAD

**Issue by cnmontreal** [githubschool/foundations-4-28-15#206]
![image](https://cloud.githubusercontent.com/assets/12156704/7375721/8565e800-eda8-11e4-98fd-8b459b0bfc49.png)

**Comment by patrickmckenna** [comment]
@wenyibing Just sent you an invite. Once you accept, you'll have access to labels (among other things).

**Comment by cnmontreal** [comment]
now I have the checkbox. thanks!

**Comment by cnmontreal** [comment]
it's done
