### ISSUE TITLE
Question on issues

### ISSUE THREAD

**Issue by sreechandran** [githubschool/foundations-4-28-15#215]
The code section in the issue automatically points to the master branch "Foundations.. " is it because this is the only master branch under the organization?

**Comment by patrickmckenna** [comment]
@sreechandran What do you mean "code section in the issue?" Issues are not tied to branches.

**Comment by sreechandran** [comment]
@PatrickBM the <> tab in the right side

**Comment by patrickmckenna** [comment]
@sreechandran Does that answer it?

**Comment by sreechandran** [comment]
@PatrickBM  Yes thanks. Can i port issues between different branches?

**Comment by patrickmckenna** [comment]
@sreechandran Issues are tied to repositories, not branches, so there's no need to port anything.

**Comment by sreechandran** [comment]
@PatrickBM Thanks!
