### ISSUE TITLE
I dont have "clone to desktop" just "download ZIP"

### ISSUE THREAD

**Issue by ebaybutler** [githubschool/foundations-4-28-15#238]
I still don't know how to add labels either.

https://github.com/ebaybutler/recipes

**Comment by patrickmckenna** [comment]
@ebaybutler You still need to accept the invitation to the githubschool org and the foundations-april team -- that's why you don't have labels, &c.

**Comment by ebaybutler** [comment]
Not sure what you mean.  I signed up already.
