### ISSUE TITLE
Question: 1

### ISSUE THREAD

**Issue by arjun911code** [githubschool/foundations-4-28-15#241]
Please provide one more demo on creating issues, branching out to fix it, merging it back. Thank you.

**Comment by rezwang** [comment]
:+1:

**Comment by rezwang** [comment]
:+1:

**Comment by wrhubert** [comment]
![image](https://cloud.githubusercontent.com/assets/8277751/7376742/70e0b0dc-eda7-11e4-89c1-e9f8cb892464.png)

**Comment by borja-king** [comment]
:+1:

**Comment by ipuigdollers** [comment]
:+1:

**Comment by pcharlan** [comment]
:+1:

**Comment by alexmoddejonge** [comment]
:+1:
