### ISSUE TITLE
Clone in desktop

### ISSUE THREAD

**Issue by cnmontreal** [githubschool/foundations-4-28-15#242]
I've installed GitHub Windows desktop.
![image](https://cloud.githubusercontent.com/assets/12156704/7376599/d62146b2-edae-11e4-9bde-470f6755195b.png)

When I click the button "clone in desktop", it opens the "Download GitHug for Windows" web page.

![image](https://cloud.githubusercontent.com/assets/12156704/7376537/63e99e5a-edae-11e4-9487-5f624a8cbebd.png)

**Comment by patrickmckenna** [comment]
@wenyibing Have you set up GitHub for Windows with your GitHub username and password?

**Comment by cnmontreal** [comment]
works fine now. thanks!
