### ISSUE TITLE
Clone to GitHub Enterprise account

### ISSUE THREAD

**Issue by hoanktran** [githubschool/foundations-4-28-15#244]
Can you clone a public repo to a GitHub Enterprise account?

**Comment by patrickmckenna** [comment]
@hoanktran That depends on your network configs. Most likely not, as the vast majority of employers put GHE behind a firewall, and don't expose it to the public internet.

You can, however, clone the repo to your local machine, then push it to your account on GHE.

**Comment by hoanktran** [comment]
Makes sense.  Thanks!
