### ISSUE TITLE
Do we need GitHub for Windows working for tomorrow's class?

### ISSUE THREAD

**Issue by GregJeffery** [githubschool/foundations-4-28-15#261]

**Comment by patrickmckenna** [comment]
@GregJeffery Tomorrow's class will be command line only. We won't be using the GUI, but you will want to use another program -- Powershell -- that gets installed alongside the GitHub for Windows app. It's a command line interface for Windows that mimics a Bash shell.

**Comment by GregJeffery** [comment]
We got the GitHub working almost. We had to use powershell commands to try and import the recipies branch. It imported a branch but I don't think it got the correct one. I couldn't follow the rest of the example from that point on.

**Comment by githubteacher** [comment]
@GregJeffery sorry for the issues during class. We recorded the session and I will do my best to post the recording today so you can review it!
